version: "3.8"
services:
  team:
    hostname: "team"
    #restart: always
    build: ./src
    command: python src/app.py
    volumes:
      - "./:/src"
    ports:
      - "5000:5000"
    expose:
      - "5000"

  